### ISSUE TITLE
method 명은 camelCase 형태로 쓰는것이 관례입니다.

### ISSUE THREAD

**Issue by ziponia** [2YeongHoon/Springboot-Mobile-Invitation-Server#1]
https://github.com/2YeongHoon/Springboot-Mobile-Invitation-Server/blob/dd410e13cd915cec7cae684202b9c7d5fbbc9749/src/main/java/com/mobileinvitation/controller/MobileInvitationController.java#L18

```
Login(x) -> login(o)
```

**Comment by 2YeongHoon** [comment]
Login -> login 메서드 명 수정
