### ISSUE TITLE
Exception 이 throw 되지 않으면, Transaction 이 Rollback 되지 않습니다.

### ISSUE THREAD

**Issue by ziponia** [2YeongHoon/Springboot-Mobile-Invitation-Server#2]
https://github.com/2YeongHoon/Springboot-Mobile-Invitation-Server/blob/dd410e13cd915cec7cae684202b9c7d5fbbc9749/src/main/java/com/mobileinvitation/service/MobileInvitationService.java#L41-L43

**Comment by 2YeongHoon** [comment]
throw 수정
