### ISSUE TITLE
@MappedSuperClass 는 abstract class 로 구현하세요.

### ISSUE THREAD

**Issue by ziponia** [2YeongHoon/Springboot-Mobile-Invitation-Server#3]
https://github.com/2YeongHoon/Springboot-Mobile-Invitation-Server/blob/dd410e13cd915cec7cae684202b9c7d5fbbc9749/src/main/java/com/mobileinvitation/model/entity/TimeEntity.java#L14-L16

`@MappedSuperClass` 는 가능 한 한, abstract class 로 구현하세요.

JPA `MappedSuperClass` 는 `상속(inherit)` 역할에 초점을 맞춰야 합니다.

abstract class 로 구현해서, 인스턴스 초기화 의 실수를 방지하는 것이 더 좋습니다.

**Comment by 2YeongHoon** [comment]
TimeEntity, abstract class로 변환하였습니다.
항상 감사합니다.
